### PR TITLE
Fixing builds: updating to latest octokit library

### PR DESCRIPTION
**Pull request by evertonfraga**
Both circleCI and Netlify are having this error:
> 10:57:42 AM: Your bundle is locked to **octokit (4.17.0)**, but that version could not be found
10:57:42 AM: in any of the sources listed in your Gemfile. 

Octokit is a library maintained by GitHub, and got pulled from the Rubygems package registry.
image.
Source: https://rubygems.org/gems/octokit/versions

### CODE REVIEW

**Comment by chriseth** [comment]
Can you also update the circleci config file?

**Comment by evertonfraga** [comment]
I am taking a look at the circleci now. That's another problem, though. The package manager (bundler) is outdated.

**Comment by evertonfraga** [comment]
@chriseth fixed.

**Comment by chriseth** [comment]
Nice, thanks a lot!

**Pull request merged**
