### PR TITLE
Uploading Solidity favicon

### PR DESCRIPTION
**Pull request by franzihei**

### CODE REVIEW

**Comment by chriseth** [comment]
We are always getting the following error from netlify:
```
12:14:54 PM: Your bundle is locked to octokit (4.17.0), but that version could not be found
12:14:54 PM: in any of the sources listed in your Gemfile. If you haven't changed sources,
12:14:54 PM: that means the author of octokit (4.17.0) has removed it. You'll need to update
12:14:54 PM: your bundle to a version other than octokit (4.17.0) that hasn't been removed in
12:14:54 PM: order to install.
12:14:54 PM: Error during gem install
```

**Comment by chriseth** [comment]
Although circleci build is fine...

**Comment by chriseth** [comment]
@franzihei isn't the resolution a bit too high for a favicon?

**Comment by franzihei** [comment]
True, let me re-upload with smaller resolution. About the failing netlify tests idk...

**Comment by chriseth** [comment]
Can you squash into a single commit?

**Comment by franzihei** [comment]
No, I can't. I'm not a developer, neither do I know how to use git. Unless somebody shows me. 😇

**Comment by evertonfraga** [comment]
Alternatively, squash can be done at merge time “Squash and merge”, if it’s enabled in repo settings.

**Pull request merged**
